services:
  go_app_dev:
    container_name: go_app_dev
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    environment:
      DEBUG: true
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "converter"
      POSTGRES_HOST: "postgres"
      POSTGRES_SSL_MODE: "disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      CONVERSION_EXCHANGE: "conversion_exchange"
      CONVERSION_KEY: "conversion"
      CONVERSION_QUEUE: "video_conversion_queue"
      CONFIRMATION_KEY: "finish-conversion"
      CONFIRMATION_QUEUE: "video_confirmation_queue"
    volumes:
      - .:/app
      - external-storage:/media/uploads

  postgres:
    container_name: database
    image: postgres:15.8-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "converter"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.11.0
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@user.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  nginx:
    container_name: nginx
    image: nginx:1.19.10-alpine
    ports:
      - 9000:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - external-storage:/media/uploads

volumes:
  external-storage:
    external: true
